import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail",
  port: 587,
  secure: false,
  auth: {
    user: process.env.SMTP_USER, // company email
    pass: process.env.SMTP_PASS, // company app password (generated by gmail)
  },
});

try {
  await transporter.verify();
  console.log("Server is ready to take our messages");
} catch (err) {
  console.error("Verification failed:", err);
}

export const sendMail = async (to:string, subject:string, text:string, html:string) => {
  try {
  const info = await transporter.sendMail({
    from: `"RYDEX" <${process.env.SMTP_USER}>`, // sender address
    to, // list of recipients
    subject, // subject line
    text, // plain text body
    html, // HTML body
  });

  console.log("Message sent: %s", info.messageId);
  // Preview URL is only available when using an Ethereal test account
  console.log("Preview URL: %s", nodemailer.getTestMessageUrl(info));
} catch (err) {
  console.error("Error while sending mail:", err);
}
}